# fly.toml generated for a static site
app = "test_page"
primary_region = "ord" # Chicago; change if you prefer





[[services]]
protocol = "tcp"
internal_port = 80


[[services.ports]]
port = 80
handlers = ["http"]


[[services.ports]]
port = 443
handlers = ["tls", "http"]
