# fly.toml generated for a static site
app = "Test"
primary_region = "ord" # Chicago; change if you prefer


[build]
dockerfile = "Dockerfile"


[[services]]
protocol = "tcp"
internal_port = 80


[[services.ports]]
port = 80
handlers = ["http"]


[[services.ports]]
port = 443
handlers = ["tls", "http"]
