name: Deploy to Fly.io


on:
push:
branches: [ "main" ]


jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Install flyctl
uses: superfly/flyctl-actions/setup-flyctl@master


- name: Deploy
env:
FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
run: |
flyctl deploy --remote-only
